name: Run Python Script and Upload to Azure Blob

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests xlsxwriter azure-storage-blob
    - name: Run script
      run: |
        python metadataFromAPI.py
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
